[package]
name = "chacha20poly1305"
version = "0.1.0"
authors = ["proelbtn <contact@proelbtn.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
byteorder = "1.4.2"
num-bigint = "0.3.1"
num-traits = "0.2.14"

